### ISSUE TITLE
01 - Tweet Streaming

### ISSUE THREAD

**Issue by parthivapsani** [MLH-Fellowship/0.1.1-BLM-Tracker#2]
Currently working on implementing Tweepy to stream tweets to a python script, will update with progress

- [X] Obtain API Keys
- [x] Create external file with API keys and other static information (and add this file to the .gitignore)
- [x] Get tweet stream functioning with test keyword
- [x] Add real keywords to additional file
- [x] Start working on pre-classifier data scrubber

**Comment by AmirYalamov** [comment]
Different parameters to filter by:

- English tweets
- location enabled on account
- relevant keywords
