### ISSUE TITLE
02 - Keras model to classify relevant tweets

### ISSUE THREAD

**Issue by AmirYalamov** [MLH-Fellowship/0.1.1-BLM-Tracker#3]
We need to take the streamed tweets for the Twitter Streaming API and classify them as movement-related tweets, then use the relevant tweet locations to create a heat map.

- [x]  retrieve tweets in proper format from Twitter 
- [ ] find pre-trained sentiment analysis model 
- [ ] retrain model with tweets from initial tweet stream
- [ ] run collected tweets through model and classify tweets as relevant or not based on sentiment analysis

**Comment by parthivapsani** [comment]
So I was talking with Cory about this, and we thought it would make sense if we took a pre-trained sentiment analysis model and retrained it a bit on some of the tweets from the initial tweet stream. Maybe we could look for a suitable sentiment model beforehand instead of training one from scratch?

**Comment by AmirYalamov** [comment]
That makes a lot of sense, I've edited the original issue to reflect our new plan :)

**Comment by parthivapsani** [comment]
- [x] Add language detection to filter out any tweets that aren't English
- [x] Scrub punctuation, emojis, and non-alphanumeric symbols out of the tweets before passing it into Keras

**Comment by parthivapsani** [comment]
Quick update here, I couldn't find any pre-trained model that I liked / worked well so I trained my own
